language: node_js
node_js:
- '0.12'
- iojs
matrix:
  allow_failures:
  - node_js: iojs
before_install:
- npm install npm@latest
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
after_script:
- npm run test:coverage
cache:
  directories:
  - node_modules
deploy:
  provider: npm
  email: k88hudson@gmail.com
  api_key:
    secure: AxkLY5mAkC9ghewo/o1nn5RbachcWnSSVADKEtHVV0VpiEu8zAqUfc7HJ72ie5VBoJQcQaUjt6sjgf/cZuj3YNpz1aJTbuZwp5ZHzi50BlF2iGkcq5QJebI7CL0itV5bZl1KDb0puBAbemLvgp/YqDJcgJ72PYW0gvGMUUt5Ga6D7dnoDvCM/5Q9qKzpRyXGcjiZt6Y9H+79n4uzOLlAIVM/bexrwKDu1QFJw0m7+nQ6Ey38ZAfd1MdY/vgykMDQhGCxaZTqF0yWhTumtB0WkZECDySA0kcVJDdWhlHcYeuFREcRuJbGozlboxzG/FgEEWhfJp4QswzZfAmMeRjq7eathR00LGb8Z6HtrFRu/jq5RVghzukK4FXxetBDGNU3rZI/4g7ETxkYJb4Zn0Nk3u0EGQHYZB9acnRXIiNXRk6HeMarTwrms1kQg/Dt8+EIcO7wtjRVzZ5pdNLizHUZ+UGnuyuKSFcj7LU27xJSCqE48bhGSxyzHGOCZEL6hLXXeltvvA/BNdpQT7kL0kuG+k9JJdtQRu2/kpklg6g/7DKOvmQWFLyXuY+FgDODD+2nqHKHP1FGlL/36zwiKuQ9a/Z54tK4hUzo+YxSabJA8iJQZCfvSo72hSj2GF8sKWniIr7BOCjZJwOW2RXlSJ0jSmAkp3voEKVbHAskNZyftL4=
  skip_cleanup: true
  on:
    tags: true
    all_branches: true
    repo: k88hudson/react-formation
