language: node_js
node_js:
- '0.12'
- iojs
matrix:
  allow_failures:
  - node_js: iojs
before_install:
- npm install npm@latest
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
after_script:
- npm run test:coverage
cache:
  directories:
  - node_modules
deploy:
  provider: npm
  email: k88hudson@gmail.com
  api_key:
    secure: KG0QUWasbBJT38owKdYY4CbZew9fcHQoCRsx8w1l2ITZPT95dkMH4upW0CNAhkhjezQ6fp/1JaH4t0Ler3lcTF/zjeCmI3Ujf66YGJHtOZE/F7Sb3QhWzBEr0XBEOyprQEyLlxO/0vH9q+T3cBYfAgxuf3nOGJeti5qcLSxRGa4j1CAayQozfGk+2/ExJ8AtX7zs8/5SvlJ8FCqsihemRNtP596TSBiQsbM1+4cXPk3NAUAmRaDdpRSzBas5jTN9yPoAFDNos0p3sahCZ35fTgUXWEj0OWIdbNbUuR0oSoqHXN/tTXF0PyX5J+/iJdEWhrCm6Dp2KRM/gQT77CkhONF681WOwDzWnYdfnW/uI84/WAcXTawPn6RfmTEF2dmywblI6kmwSKhJov3UpFnLwBdhXKTEvcj/Uw0J94nyceVD5fm1ZQKq4Z5NfdN+hwqRonUXjEp0lUgQIeeGNpz95KKRiEjUEXmcXiEU4z4b/T459Xw6Mu6qup/AIuEX/83Yir1DAeU1bRObAS0pnF2A5sc8E0JZm5iE2FBFDnlv8IZ80OGsCgH4SY/9GF+mevceUX09ucobOoZZN/ZCnKqEUqQdTVEJPJE0CcJSyCLOg1ywAfghGPq3q5KRr7YiViNLmUsDFeuzevx8VreNnemy4wCj09+ivCcp5Lb5cZ/Vp+I=
  skip_cleanup: true
  on:
    tags: true
    all_branches: true
    repo: k88hudson/react-formation
